### ISSUE TITLE
Request: when showing subtitles, auto-position them above the playback controls

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#100]
When the playback controls appear, the subtitles should be above, to avoid not showing them.
If this is impossible (because not enough space, for example) the controls could at least be semi-transparent.

**Comment by Ivshti** [comment]
We've decided against that since we use multiple players (MPV, HTML5, youtube) and implementation will be complicated

**Comment by AndroidDeveloperLB** [comment]
@Ivshti Can you please at least add a setting to hide it immediately when the video plays then, to avoid overlapping?
Or to make the controls semi-transparent?
