### ISSUE TITLE
Request : Problems with the building of Stremio under Chromebook Acer 514

### ISSUE THREAD

**Issue by Jules76-droid** [Stremio/stremio-shell#105]
I tried on my computer to built Stremio, following the instructions (https://github.com/Stremio/stremio-shell/blob/master/DEBIAN.md) given by vejeta.
However, when I try to install missing dependencies, entering "sudo apt-get install libqt5webview5-dev", the terminal answer "E: Unable to locate package libqt5webview5-dev". Do you know why?

**Comment by danilolutz** [comment]
maybe is too late but, should resolve: `sudo apt install qtwebengine5-dev`

**Comment by Jules76-droid** [comment]
No thanks, it was not too late and it was useful

Le ven. 21 févr. 2020 à 20:14, Danilo Lutz <notifications@github.com> a
écrit :
