### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by p1u3o** [Stremio/stremio-shell#109]
Hello!

I run Fedora Silverblue where applications are primary packaged as Flatpak and wanted to run Stremio. So I put together some files that build Stremio 4.4.77 (as I understand, the beta version) as a native Flatpak package https://github.com/p1u3o/com.stremio.Stremio. The appdata file should ideally be upstream as it will benefit other packaging formats.

Flatpak is a cross-distro package technology that lets you build and distribute packages that run on almost every distribution and has first-class support in Fedora, Elementary, Linux Mint and other distros.

Flathub, the largest Flatpak repository, prefers that upstream maintains or has involvement in the Flatpak package, which is why I'm posting here as it may be viable for the package to become official. If not, as a user, I'll be maintaining it for my own personal usage.

**Comment by TRtomasz** [comment]
Hi, thanks for your efforts, we will check prepared flatpak package soon!

**Comment by p1u3o** [comment]
Thanks for the response! Let me know if there's anything I can do to help.

**Comment by p1u3o** [comment]
Any progress with this?

I wouldn't mind submitting the manifest I built to Flathub and then passing over control or switching to an official manifest when ready.

**Comment by TRtomasz** [comment]
Hi @p1u3o  i think @core1024  tested it and there are two issues. 1. Tray icon wasn't working 2. App didn't respect system theme so cursor was different. Do you think you are able to fix these issues?

**Comment by p1u3o** [comment]
1) Should be fixable, I had to include a one line patch to disable minimizing to tray though (is this really needed enabled by default?)
2) This sounds like a Qt bug, I haven't seen this on GNOME 3.34. cc @tingping

**Comment by TingPing** [comment]
1. You are missing permissions for StatusNotifer, Qt's implementation is kinda broken but you can try: `"--talk-name=org.kde.StatusNotifierWatcher"`, it may need `--own-name=org.kde.StatusNotifierItem-2-1` (which is the broken bit).

**Comment by TingPing** [comment]
I have no idea how KDE sets the cursor theme, GNOME uses XSettings which is why it works.

**Comment by p1u3o** [comment]
I had a build error with io.qt.qtwebkit.BaseApp//5.13 when I first put together the manifest, but I will try again.

**Comment by TingPing** [comment]
Webengine and WebKit are two completely different components. If the application supports webengine then use it.

**Comment by GustavoPeredo** [comment]
Any progress since January the 14? I use Clear Linux and it is almost impossible to install Stremio from source in it, however a flatpak image would REALLY help (and make it easier to people in other distros to install it).

**Comment by p1u3o** [comment]
> 
> 
> Any progress since January the 14? I use Clear Linux and it is almost impossible to install Stremio from source in it, however a flatpak image would REALLY help (and make it easier to people in other distros to install it).

I think the only left over issue was on KDE the cursor theme not working. However, there's nothing stopping you from grabbing the Flatpak builder files and building/installing it yourself, the instructions are on the manifest repo.

**Comment by warutsutsu** [comment]
Hey, well done! Everything is working! Just noticed the same issue with mouse cursor not being the same. I'm running Fedora 32 (Silverblue 32, on other machine) with Gnome 3.36 but I also have this same bug with flatpak Krita, which is qt as well. Starting to guess that it is going to happen with every KDE based app. Don't know. Thank you for packaging it. Hopefully it will be on flathub soon!

**Comment by BeatLink** [comment]
hey! any plans on uploading this to flathub?

**Comment by Barraguesh** [comment]
> hey! any plans on uploading this to flathub?

Was going to ask this. Flatpak works flawlessly, I would like to have it on Flathub to be able to include it in my setup script plus I think having a centralized store for flatpaks is another plus of using them.

**Comment by core1024** [comment]
I did a PR to [Flathub](https://github.com/flathub/flathub/pull/2047).

**Comment by BeatLink** [comment]
Awesome! Waiting with bated breath!

**Comment by core1024** [comment]
You can now install Stremio from flathub https://flathub.org/apps/details/com.stremio.Stremio

**Comment by BeatLink** [comment]
No way! Awesome!
