### ISSUE TITLE
Refactor CI process

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-shell#117]
## Problem

We use 4 separate repos (5 if you count this one) to produce desktop builds. The versioning system is unintuitive and complicated. The process is too.

## Solution

Consolidate all desktop builds (CI, build steps) into this repo.

This will require:

* [x] instead of CI on `stremio-{osx,win,linux}-installer`, all the builds will be triggered from CI installed on this repo (AppVeyor for Windows, Travis for Linux/Mac, Actions for Mac)
* [x] revised versioning policy: tags in this repo will be considered releases of the desktop app; the version of the .exe/.dmg will be taken from the VERSION set in `stremio.pro`, and the tag to which we upload (in `dl.strem.io/PLATFORM/TAG/FILENAME`) will be the tag/branch name
* [x] there are 3 certificate files (mac - installer, mac - code sign, windows - code sign) that need to be moved into this repo; we will symmetrically encrypt them with `gpg` and set the key as a CI secret
* [x] all the `gulp` steps in `Stremio/stremio` need to be re-written as CI steps
* [ ] ~~implement a pre-tag git hook that doesn't allow a tag to be made if it's version mismatches the version in `stremio.pro`~~
* [x] move `release-version.js` to this repo (`scripts/` dir); the restrictions (e.g. that the shell version has been bumped) are no longer needed
* [x] get rid of the old stremio-{osx,win,linux}-installer repos and their 24 hour automation (triggers)

Furthermore, some things need to be improved about the GitHub Actions build for Mac:
* [x] fix_osx_deps might not be needed
* [ ] ~~notarization needs to properly poll status~~

**Comment by core1024** [comment]
There are some points that either cannot be done or we don't gain anything from doing it: 
* Implementing pre-tag hook is not feasible as the point of the git hooks is to stay locally on the developer's PC. They are also not synced with the repo.
* Reading the notarization status is [technically done](https://github.com/Stremio/stremio-shell/blob/f671af27654d5adac7a6d623280faa04b65910f3/mac/notarizer.sh#L45). There is no need for additional code complication. The commented out code above the line that checks and prints the status in the log is much more complex and error prone.

**Comment by Ivshti** [comment]
Agreed

Closing this, as the PR to move the script has been merged
