### ISSUE TITLE
Shell does not work on Big Sur

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-shell#147]
**Description**
Big Sur beta users reported that they are not able to start application on Mac Os Big Sur. Before apple release it officially we should check and fix this issue. Planned release date is is not know, it should happen in September/October.

**Comment by markomitranic** [comment]
Heres a console report of it. Seems that some security had changed in macOS

```
Prompting policy for hardened runtime; service: kTCCServiceCalendar requires entitlement com.apple.security.personal-information.calendars but it is missing for RESP:{ID: com.smartcodeltd.stremio, PID[5645], auid: 502, euid: 502, responsible path: '/Applications/Stremio.app/Contents/MacOS/stremio', binary path: '/Applications/Stremio.app/Contents/MacOS/stremio'}, ACC:{ID: com.apple.mdfind, PID[5648], auid: 502, euid: 502, binary path: '/usr/bin/mdfind'}, REQ:{ID: com.apple.mds, PID[85], auid: 0, euid: 0, binary path: '/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds'}
```

**Comment by Ivshti** [comment]
@TRtomasz did we test whether disabling the local addon scraping will solve this?

**Comment by omfgnuts** [comment]
Any updates on Big Sur fixes?

Old one gets updated and stops working constantly :(

**Comment by Ivshti** [comment]
We've opened another issue to track the build status: #153

**Comment by Ivshti** [comment]
There is a big sur build ready here: https://dl.strem.io/shell-osx/v4.4.120/Stremio+4.4.120.dmg
