### ISSUE TITLE
Stremio crashes on minimize-maximize window - arch linux

### ISSUE THREAD

**Issue by laurentiucalonfir** [Stremio/stremio-shell#162]
Hi everyone! I installed stremio in arch linux with pamac-aur, and when i try to minimize and then maximize window, it crashes.

**Comment by core1024** [comment]
Perhaps this is due to known issue in Qt 5.15.1 - https://bugreports.qt.io/browse/QTBUG-86599

You can either downgrade Qt or wait for fix to be released.
