### ISSUE TITLE
Stremio application not opening

### ISSUE THREAD

**Issue by bored-user** [Stremio/stremio-shell#163]
I'm on Kubuntu 20.04, using Qt 5.12.8, KDE 5.18.5 and kernel 5.4.0-51-generic. When I open Stremio, it simply closes right after. When I try through the terminal, it throws `error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`. Already tried downloading the deb package (and installing) again and the appimage file; neither worked (same error)

**Comment by The-SamminAter** [comment]
I get a similar error on Linux Mint 20 and the same kernel as @bored-user. When I try to open Stremio, nothing visible happens, and when I try to run it through terminal, I get the following:
```
stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory
```

I've installed all dependencies, and am using the latest .deb for Debian/Ubuntu (v4.4.116-1).

**Comment by bored-user** [comment]
> I get a similar error on Linux Mint 20 and the same kernel as @bored-user. When I try to open Stremio, nothing visible happens, and when I try to run it through terminal, I get the following:
> ```
> stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory
> ```
> 
> I've installed all dependencies, and am using the latest .deb for Debian/Ubuntu (v4.4.116-1).

I just changed to Kubuntu (few days ago). Before that, I was in Linux Mint 20 as well (I don't remember the kernel but I have a timeshift backup, I'll try to see if I can find and report back here), but Stremio worked fine there

**Comment by The-SamminAter** [comment]
I have now upgraded kernel v5.4.0-52.57, and am still having the same issue.

**Comment by bored-user** [comment]
Am currently on `5.4.0-52-generic` (it still doesn't work).

**Comment by bored-user** [comment]
@The-SamminAter I managed to fix it!
I first ran `sudo /sbin/ldconfig -v`; then, I searched (`sudo apt search --names-only`) for packages named `libmpv` and installed `libmpv1` and `libmpv-dev`; and, finally, ran `sudo /sbin/ldconfig -v` once again.
Now, Stremio opens normally and it seems to be working as expected.

**Comment by FinixFighter** [comment]
> @The-SamminAter I managed to fix it!
> I first ran `sudo /sbin/ldconfig -v`; then, I searched (`sudo apt search --names-only`) for packages named `libmpv` and installed `libmpv1` and `libmpv-dev`; and, finally, ran `sudo /sbin/ldconfig -v` once again.
> Now, Stremio opens normally and it seems to be working as expected.
> Edit: I followed [this](https://itsfoss.com/solve-open-shared-object-file-quick-tip/) itsfoss article.
> 
> I'll close the issue; however, if you have any problems while installing, feel free to reopen it

I did your same steps but it still doesn't start.

**Comment by The-SamminAter** [comment]
My issue has been resolved by downloading hand installing libx264-152 manually, as for some reason apt wasn't able to find that package. 

@FinixFighter what error are you getting?

**Comment by FinixFighter** [comment]
> @FinixFighter what error are you getting?

I can't test on that system anymore, sorry! On my pc it worked, I had to manually install libx264.152 too.
