### ISSUE TITLE
Various Errors In Stremio On Linux Including Application Failing To Start, "The Source Is Poorly Available", Etc.

### ISSUE THREAD

**Issue by bhavitsharma** [Stremio/stremio-shell#167]
I have been recently experiencing a ton of errors from stremio. I compiled stremio-shell with qt 5.14 (if that matters) using the instructions provided in debian doc, and I keep failing with the following error.

```qml: Auto-updater: skipping, possibly not running an installed app?
[libmpv_render] GL_VERSION='4.6 (Compatibility Profile) Mesa 20.1.2'
[libmpv_render] Detected desktop OpenGL 4.6.
[libmpv_render] GL_VENDOR='Intel'
[libmpv_render] GL_RENDERER='Mesa Intel(R) UHD Graphics 620 (KBL GT2)'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.60'
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'vaapi-egl'
[libmpv_render/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'vdpau-gl'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'drmprime-drm'
[libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display.
[libmpv_render] Loading failed.
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QObject::~QObject: Timers cannot be stopped from another thread
```
So I manually started the server, and ran the server using `node server.js` and then opening the link `app.strem.io/shell-v4.4/#/` in my browser. So far so good - this worked fine for a couple of months, until recently, this stopped working too :( For every addon, it just fails to load with the error "This source is poorly available or ". Sometimes, when it does load, the audio doesn't works which is weird. 

I thought maybe this is a problem with stremio in general but the same addons was working perfectly fine with my android phone and it worked so smoothly. I even tried to download the same torrent on my linux system, and it downloaded fine in just few minutes... Is there any way I can debug this?

**Comment by TRtomasz** [comment]
Hi @bhavitsharma, sorry for such late reply
You might try to start stremio and try to open link like this in your browser 
http://127.0.0.1:11470/0e165d85a8d74c94c8c1af3ad2acfdb8ffbacc59/0/ port might be different if you have something on this port running 
It should start downloading video using stremio engine
