### ISSUE TITLE
Autoupdater: fix check whether it's installed on macOS when running through Rosetta 2

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-shell#177]
when running on rosetta2, the autoupdater does not know that stremio is installed because the binary location is different

**Comment by TRtomasz** [comment]
Can this be done at all? Someone might run not installed app and still have another one installed in the `/Applications` directory
For sure it is possible to detect if rosetta is running [link](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment#3616845)
Maybe with current changes to the autoupdater this is no longer needed?

**Comment by Ivshti** [comment]
we should be able to distinguish between someone running from outside applications (in general) and someone running through rosetta2

the new changes do not affect this, it's still required

**Comment by TRtomasz** [comment]
Ok, first solution could be  run`lsof -c stremio` and look for `/Applications/Stremio.app/Contents/MacOs/stremio`

**Comment by jaruba** [comment]
I found a post on Apple's forum that suggests using similar code as to the one Tomek found (to find out if the app is running in Rosetta2 or not): https://developer.apple.com/forums/thread/653009

This one seems a bit more complete though and includes comments
