### ISSUE TITLE
Autoupdater: fix for isOnline on Windows

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-shell#178]

**Comment by TRtomasz** [comment]
i thought this was fixed with https://github.com/Stremio/stremio-shell/pull/172

**Comment by TRtomasz** [comment]
@core1024  can you confirm?

**Comment by core1024** [comment]
I think so. This issue does not describe what exactly is the problem.  Could be something different.

**Comment by Ivshti** [comment]
It's the same

**Comment by Ivshti** [comment]
didn't think the issue was merged
