### ISSUE TITLE
Stremio RPM fails to install on Fedora 33

### ISSUE THREAD

**Issue by eduararley** [Stremio/stremio-shell#180]
RPM fails to install. It complains about libQt5Quick.

I've rebuilt RPM for Fedora 33 x86-64. Instructions are here:

```
# Dependencies
# qt5-devel has changed to qt-devel 
yum -y install git mpv-libs-devel qt-devel qt5-qtwebengine-devel openssl-devel nodejs rpmdevtools librsvg2-tools

cd /tmp
git clone --depth 1 --branch v4.4.120 https://github.com/Stremio/stremio-shell.git
cd stremio-shell
git checkout -b master
cd distros/Fedora

# Change qt5-devel to qt-devel
sed -i 's/qt5-devel/qt-devel/g' stremio.spec
./mkconfig.sh
./package.sh
```

After this process, RPM will be in ~/rpmbuild/RPMS/x86_64. I've uploaded my copy here
[stremio-4.4.120-1.fc33.x86_64.rpm.gz](https://github.com/Stremio/stremio-shell/files/5644231/stremio-4.4.120-1.fc33.x86_64.rpm.gz)

**Comment by esercankutay** [comment]
no success with flatpak installation either. stremio crashes on both wayland and x11 session

**Comment by TRtomasz** [comment]
Closing, now recommended way to install Stremio on fedora is to use flatpak package.
