### ISSUE TITLE
Rebrand node.exe on Windows

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-shell#183]
Some antivirus programs are detecting node.exe as malware. Furthermore, firewalls are asking the user if they want to whitelist node.exe upon stremio startup and they often decline. So we should:

* ensure node.exe is codesigned with our certificate
* rebrand it by renaming it and changing the resources, as part of the build process

**Comment by jaruba** [comment]
Can we call it `netflix.exe`?
