### ISSUE TITLE
Allow using mpv built from git

### ISSUE THREAD

**Issue by Kabouik** [Stremio/stremio-shell#201]
There are many reasons one would want to prefer custom mpv builds over system mpv, namely using advanced filters like vapoursynth required by SVP4, but also other useful ffmpeg filters. 

Yet, if I build mpv with the options I want and then make it so it is found by Stremio (either by editing `/path/to/mpv` in `server.js` or by symlinking `/usr/local/bin/mpv/` to `/usr/bin/mpv`), Stremio will fail to cast to mpv. I haven't noticed any error in terminal, but when trying to open the current stream in mpv, Stremio will just spam:
 ```
-> POST /casting/mpv/player
-> POST /casting/mpv/player
-> POST /casting/mpv/player
```
in the terminal as if it was working, except no mpv window is opened.

Is there a way to achieve this that I may have missed? Allowing using any mpv binary would also probably solve #81.

Note that this used to work some months (maybe a year?) ago, as I did use SVP4 with mpv from Stremio streams. But perhaps that was before Stremio did some changes with libmpv.

**Comment by Kabouik** [comment]
Stremio seems to be using a different build of mpv (0.33 dirty), no matter what I do with mpv binaries in `/usr/bin`. Is it builtin Stremio or is the binary accessible somewhere so that I can change it?

**Comment by core1024** [comment]
After quick check I discovered that MPV have dropped the support of spaced arguments. I just replaced my `/usr/bin/mpv` with the following script:

```
 ~ $ cat /usr/bin/mpv
#!/bin/bash

echo "$@" > ~/mpv-exe.txt
```

Then tried to cast and after that I've tried to launch MPV with the arguments from that file:

```
~ $ cat mpv-exe.txt
--start 0 --no-terminal http://127.0.0.1:11470/08ada5a7a6183aae1e09d831df6748d566095a10/5
~ $ /usr/bin/mpv-orig --start 0 --no-terminal http://127.0.0.1:11470/08ada5a7a6183aae1e09d831df6748d566095a10/5
Error parsing commandline option start: option requires parameter
Make sure you're using e.g. '--start=value' instead of '--start value'.
Exiting... (Fatal error)

```

Then I looked at the MPV RELEASE_NOTES and I saw a line like this

> options: remove deprecation warning for "-foo bar" syntax

As a temporary workaround (till we fix that) you can make `/usr/bin/mpv` a shell script. Something like that will do the job:

1. First backup your mpv:

```
sudo cp /usr/bin/mpv /usr/bin/mpv-orig

```

2. Put shim script in place of mpv binary:

```
sudo sh -c 'cat > /usr/bin/mpv'
#!/bin/bash

mpv-orig $(sed -r 's/(--[^ ]+)[ ]([^-])/\1=\2/g;s/=([^=]*)$/ \1/'<<<"$@")
^D
```

The last line indicates that you need to press Control+D on a blank line to save the script

3. Lastly make the new script executable:

```
sudo chmod a+x /usr/bin/mpv
```

Stremio will be able to cast to MPV again. We just have not noticed that change in MPV player.

**Comment by Kabouik** [comment]
Thanks a lot for looking into it. So I assume this should solve the cast to mpv problem when using `/usrbin/mpv`, but in my case Stremio just ignores whatever I have in `/usr/bin/mpv` because it is using its own builtin mpv 0.33.0-dirty (I can see that when launching Stremio in terminal). It is indeed written [here](https://blog.stremio.com/stremio-4-is-out/) that Stremio now uses its own mpv. Does yours installation of Stremio actually use your external mpv? That's exactly what I would like to do, and then your fix above could restore the cast feature.

**Comment by core1024** [comment]
You need to right click in player and select mpv in order to launch the one located in `/usr/bin`. Stremio uses only libmpv for it's own player so mpv related stuff in logs is irrelevant when casting to external player.

**Comment by Kabouik** [comment]
Oh, that's great to know, thanks! That means I was doing the right thing but the casting problem was preventing me from seeing my custom mpv from loading. I'll try your script replacement immediately!

**Comment by Kabouik** [comment]
Was the issue with mpv syntax (no longer supporting spaced arguments) fixed @jaruba? I didn't see it in the recent commits.

**Comment by core1024** [comment]
You don't see commits because the issue affects the server (private repo) and not the shell. Next release will feature the fixed server so no additional patches will be needed.

**Comment by Kabouik** [comment]
Great, thanks for the update!
