### ISSUE TITLE
Bug: allow going back when buffering before playback start

### ISSUE THREAD

**Issue by rijnhard** [Stremio/stremio-shell#204]
If a stream is buffering or trying to determine if it can stream, and you decide to cancel, you can't, ui is basically locked, until it times out naturally.

It should allow cancellations at any point

**Comment by jaruba** [comment]
There is a "Back" button in the top left when the video player is loading

**Comment by rijnhard** [comment]
yes, and it works except on the initial video load/buffer, before playback
starts for the first time.
Maybe its the plugin (torrentio).

**Comment by jaruba** [comment]
It works fine for me through the initial buffering period also. The addon you use has nothing to do with it. Go to Settings and tell me all the versions that are written in the bottom left of the settings view.

Also, what OS are you running?

**Comment by rijnhard** [comment]
mmm
just realised I had two versions installed.
Not sure which one I was running, I will test tonight and confirm.

But for completeness:
Ubuntu 20.04.2 LTS
5.4.0-66-generic x86_64

And the two flatpack versions I had
```
Stremio    com.stremio.Stremio    4.4.77     beta      stremio-origin
system
Stremio    com.stremio.Stremio    4.4.120    stable    flathub
system
```

**Comment by rijnhard** [comment]
Problem solved in .120

Looks like it was just because because I was on an old version. Apologies
for the silly issue.
