### ISSUE TITLE
Year filter needs to be updated for 2021

### ISSUE THREAD

**Issue by qbss** [Stremio/stremio-shell#214]
Year filter needs to be updated for 2021 and possibly adding sub-filter options such as 30, 60, 90, 120, + days or 1,2.3, + months old, new release, in theater, etc. could useful too.

**Comment by qbss** [comment]
I'll have to research more before creating a pull request and attempting to contributing an update myself, but in general would year/catalog "releaseInfo", etc. filtering reside under the shell or the addon repo sections?

**Comment by CreativeDad** [comment]
The desktop app has just had an update but still no 2021 date added, will have to keep using the addon for now

**Comment by qbss** [comment]
I just manually updated an Ubuntu flatpak installation and it looks like it has now been updated with the 2021 filter.   Thanks to those involved with updating it.
