### ISSUE TITLE
Update AUR Dependencies And Fix release.makefile

### ISSUE THREAD

**Issue by M1ndo** [Stremio/stremio-shell#215]
Recently PKGBUILD results into broken build , the first issue is a missing dependency (cmake) and the other issue is in release.makefile which downloads server.js into the $HOME Folder.
Steps To Fix PKGBUILD:
- Update Dependencies By Adding (cmake) since it's necessary to compile stremio .
- patching release.makefile and adding 
""" SERVER_JS := $HOME/server.js """ .

**Comment by jaruba** [comment]
@core1024

**Comment by core1024** [comment]
I don't see issues with server.js. Indeed I forgot about the `cmake` dependency.

**Comment by M1ndo** [comment]
@core1024 after investigating a bit , the issue was coming up from a sandboxed wget in my arch , which resulted into server.js being in $HOME , I apologize for that and not taking enough time investigating . this issue can be closed .

**Comment by core1024** [comment]
Thank you for the `cmake` finding. Closing the issue
