### ISSUE TITLE
Downloading erratic 

### ISSUE THREAD

**Issue by rijnhard** [Stremio/stremio-shell#227]
This is gong to sound strange, but on 4.4.70 this issue did not occur and on 4.4.144 it does (flatpak linux).

When using the torrentio addon the download indicator shows the speed of download and the percentage. Well at full speed (as reported by the download) a 3gb file would be perfectly streamable, and now (at full speed) a 1gb file is BARELY streamable.

The % complete indicator actually jumps DOWNWARDS randomly like 7.8% - > 7.65%. And it constantly does these small downwards jumps in completeness.

The other strange thing is that a 2gb reported file size (in the listings not while watching) will end up showing its downloaded a total of like 2-4x the file size (as reported by the player).

**Comment by rijnhard** [comment]
Anything I can do here to provide more information?

**Comment by jaruba** [comment]
I bet that this only happens to some torrents though, the issue here is most probably torrent poisoning. By this I mean that some malicious peers are intentionally sending wrong torrent pieces, these pieces might be counted towards the sum of the full download, but than disregarded as they are deemed to be wrong. This would be very hard to fix, you might be able to reduce the damage of these peers by increasing the max connections as described in this article: https://blog.stremio.com/modify-bittorrent-settings/

**Comment by rijnhard** [comment]
wow,

I feel soo dirty.

I'll confirm but I don't think so, because even when we watch pretty
obscure content it still happens, maybe not as aggressively though.

**Comment by jaruba** [comment]
@rijnhard 

I apologise for dismissing this issue so early and presuming torrent poisoning. We found a [big ancient bug](https://cdn-prod.servicemaster.com/-/media/Feature/Terminix/Blogs/512pxArthropleuraParcoNaturaViva.jpg) in our torrent engine and have recently fixed it, this is very likely to have been the issue affecting your case also.

The fix will be added to our next desktop and android releases, thank you for being one of the users that brought this to our attention.

**Comment by rijnhard** [comment]
perfect, if you tell me the release version number when it is released I will test and revert back.

**Comment by rijnhard** [comment]
also LOOOOOOOOOOL

**Comment by jaruba** [comment]
@rijnhard if you tell me your OS, I can tell you how you can test the changes before our official release.

**Comment by rijnhard** [comment]
Ubuntu 20.04.1

**Comment by jaruba** [comment]
@rijnhard 
- close Stremio (from the tray icon too)
- download this file: https://dl.strem.io/four/master/server.js
- replace `/opt/stremio/stremio.js` with the downloaded file
- start Stremio

**Comment by jaruba** [comment]
@rijnhard or are you using flatpak? if so then the location of server.js will be different

**Comment by rijnhard** [comment]
Using flatpak, but I think I can figure it out.

**Comment by core1024** [comment]
It should be in `~/.local/share/flatpak/app/com.stremio.Stremio/x86_64/stable/active/files/opt/stremio/server.js`

**Comment by rijnhard** [comment]
Was in /var/lib but so far it looks a LOT better, can clearly see a
difference.

**Comment by jaruba** [comment]
@rijnhard happy to hear it!

**Comment by jaruba** [comment]
@rijnhard can you confirm that it still works better?

**Comment by rijnhard** [comment]
YES! definitely, I have no issues streaming fairly large files and speeds that flatten all my bandwidth.
