### ISSUE TITLE
[UNSOLVED] Can't install dependency of  libfdk-aac1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by phackwer** [Stremio/stremio-shell#230]
If you have a dist-upgrade'd Ubuntu 20.04, you only have  libfdk-aac2 available. 

Can't install .deb

$ sudo dpkg -i stremio_4.4.135-1_amd64.deb
(Reading database ... 279624 files and directories currently installed.)
Preparing to unpack stremio_4.4.135-1_amd64.deb ...
Unpacking stremio (4.4.135-1) over (4.4.135-1) ...
dpkg: dependency problems prevent configuration of stremio:
 stremio depends on libfdk-aac1 (>= 0.1.5); however:
  Package libfdk-aac1 is not installed.

dpkg: error processing package stremio (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 stremio
 
 
 Trying to solve the dependency, I've got this:
 
$ sudo apt install libfdk-aac1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libfdk-aac1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libfdk-aac1' has no installation candidate

Installing libfdk-aac install 2 and dev but not 1.

**Comment by phackwer** [comment]
Solved like this:

```
wget http://ftp.osuosl.org/pub/ubuntu/pool/multiverse/f/fdk-aac/libfdk-aac1_0.1.6-1_amd64.deb
sudo dpkg -i libfdk-aac1_0.1.6-1_amd64.deb 
sudo dpkg -i stremio_4.4.135-1_amd64.deb
```

**Comment by phackwer** [comment]
Install that and I have audio. Had to put in fullscreen to get video after video started. Then I can now watch it FS or not. So... BUG! :-D

**Comment by phackwer** [comment]
Issues just keep coming... Interface does not refresshes/rerenderes 

![image](https://user-images.githubusercontent.com/4871786/113358259-5eefe400-933d-11eb-9765-08f7d7c6730e.png)

**Comment by phackwer** [comment]
![image](https://user-images.githubusercontent.com/4871786/113359773-68c71680-9340-11eb-966d-3af0e759e0c0.png)
?

**Comment by phackwer** [comment]
![IMG_20210401_233833](https://user-images.githubusercontent.com/4871786/113361417-d9236700-9343-11eb-8e81-079f72a12e91.jpg)

I can't even make screenshots to show how bad things went!

**Comment by core1024** [comment]
Hello. In order all dependencies to be satisfied easily, you need to enable the restricted repo. It is needed for codecs. 
![image](https://user-images.githubusercontent.com/1193870/113410909-27288100-93bd-11eb-95f1-6a7b6cb1c984.png)

The other issues you have are probably due to video divers. You can try installing the proprietary drivers for your GPU and see if that solves the issue.

**Comment by phackwer** [comment]
About Ubuntu repos, I always had then enabled:

![image](https://user-images.githubusercontent.com/4871786/113441995-23a9ef80-93e7-11eb-9a10-875809c9bb12.png)

I can't use the proprietary drivers, they won't work with my screens setup:

![image](https://user-images.githubusercontent.com/4871786/113442029-31f80b80-93e7-11eb-9446-323b464c3f2c.png)

**Comment by core1024** [comment]
If you have had multiverse enabled then the only reason I can think of is that you have forgotten to `apt update` beforehand.

**Comment by nyym** [comment]
I had the same issue with package `libfdk-aac1` on Debian testing, my only option was to take the advice from #152 and install Stremio v4.4.106, which I recommend for Ubuntu 20.xx

[](https://dl.strem.io/linux/v4.4.106/stremio_4.4.106-1_amd64.deb)

**Comment by nyym** [comment]
I had the same issue with package `libfdk-aac1` on Debian testing, my only option was to take the advice from #152 and install Stremio v4.4.106, which I recommend for Ubuntu 20.xx

https://dl.strem.io/linux/v4.4.106/stremio_4.4.106-1_amd64.deb

**Comment by phackwer** [comment]
@core1024: I run apt dist upgrade from time to time, it's definitely not a problem with me being outdated or not. And trust me: I work with linux flavors since 1996, so, don't need to tell me to run "apt update". Problems are definitely related to the render component version being used now. Something has changed and for the worst. I can get video if after the playback I go in and out of full screen. Subtitles are messed up and start pilling up as presented, UNLESS they are embedded (which is weird, why the embedded subtitles uses a different rendering? Why?) So, those problems can we "workarounded" by users, but still they are there.

@nyym: you are correct about the versionin, I had to downgrade to a previous version I had backed up on one of the HDs I had around here.

ph4ckvv3r@ph4ckvv3r-XPS-15-9570 ~> apt list | grep stremio
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
stremio/now 4.4.116-1 amd64 [installed,local]

Unfortunately I could not rewrite the link you sent to get 116 instead of 106. I honestly have no clue why I had this .deb backed up here, but 116 works fine. I just keep getting bugged by the "upgrade" message. Long time ago there were a name for this:

NAG SCREEN.

I will close this as UNSOLVED

**Comment by phackwer** [comment]
@nyym they got be joking... apparently updating the APIs has some requirement to mess up the playblacks. Cinemeta plugin is dead. And since it's a base one, Stremio is dead. 

![image](https://user-images.githubusercontent.com/4871786/114783922-57cfc980-9d72-11eb-8c82-0e48f56d34bf.png)

**Comment by phackwer** [comment]
That's what the Uninstall button triggers
![image](https://user-images.githubusercontent.com/4871786/114784014-7df56980-9d72-11eb-9a7f-6932c96aa508.png)

**Comment by aasutossh** [comment]
Download the .deb file from here and install it. https://www.ubuntuupdates.org/package/core/focal/multiverse/base/libfdk-aac1

After that install the streamio. Works fine.

**Comment by Kyoro93** [comment]
I created a script to solve this problems and install stremio:
https://github.com/Kyoro93/stremio-install-ubuntu-22.04

**Comment by tiagofrancafernandes** [comment]
For Ubuntu 20.04 and required `libfdk-aac2`:

```sh
wget https://launchpad.net/ubuntu/+archive/primary/+files/libfdk-aac2_2.0.2-1_amd64.deb

sudo apt install ./libfdk-aac2_2.0.2-1_amd64.deb
```

Source:
https://launchpad.net/ubuntu/+source/fdk-aac



The Jammy Jellyfish           (supported)
--
2.0.2-1

Expand [The Jammy Jellyfish]
2.0.2-1

Download and install

**Comment by SantiiRepair** [comment]
@tiagofrancafernandes thank you!

**Comment by AshutoshSajan** [comment]
facing the same issue
