### ISSUE TITLE
unable to compile in mx linux 19.3

### ISSUE THREAD

**Issue by ajnabishaqs** [Stremio/stremio-shell#232]
when trying to execute the command - "make -f release.makefile", i am getting error 127 and error message is as below.

mkdir -p build
cd build && cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="" ..
/bin/sh: 1: cmake: not found
make: *** [release.makefile:36: build/stremio] Error 127

**Comment by core1024** [comment]
Hello.
From what I see, the error speaks for itself. You don't have `cmake` installed on your system. For reference of all the dependencies you can check some of the docker files in the `distros` directory.

**Comment by ajnabishaqs** [comment]
ok so somehow i managed to install qmake and still getting an error. attaching to log here.
[CMakeOutput.log](https://github.com/Stremio/stremio-shell/files/6348629/CMakeOutput.log)

**Comment by ajnabishaqs** [comment]
running the code `make` instead of `make -f release.makefile` seems to have fixed the issue. thank you core1024
