### ISSUE TITLE
[Windows]Stremio prevents system from going to sleep mode when video is paused

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-shell#240]
**Description**
When stremio player is paused app still prevents system from going to sleep mode.
Checked on windows.

**Comment by Araxeus** [comment]
It also blocks if the app is minimized

**Comment by core1024** [comment]
Fixed in https://github.com/Stremio/stremio-shell/pull/268

**Comment by asafm7** [comment]
Stremio is still preventing the screen from turning off after the set time under power settings (Windows 11)
