### ISSUE TITLE
Latest Server.js does not support Remote Access 

### ISSUE THREAD

**Issue by ashwarsadh** [Stremio/stremio-shell#242]
In Older Versions of server.js like 4.2.3, it was possible to just open port 11470 , then open http://app.strem.io/shell-v4.4/#/ on any browser on any device and enter server url in settings and Stremio used to work fine.

In newer server.js versions, it seems remote access is only enabled for Https endpint, on port 12470, but Node https Server fetches certificate for localhost only and if we try accessing from remote IP, it does let access due to certificate mismatch.
In Desktop Clients, https url is shown, but it also only works in LAN network, unless server is directly exposed to internet , having a public IP

So, please provide a workaround so that a public url with proper ssl certificate is generated which Stremio browser url can access remotely as well. 

This is output of node server.js

hls executables located -> { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /root/.stremio-server
Enabling casting...
Discovery of new external device "mpv" - MPV
(node:4173) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use node --trace-deprecation ... to show where the warning was created)

EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
HTTPS: Request error Could not get a valid HTTPS certificate
HTTPS: Request error Could not get a valid HTTPS certificate
HTTPS: Request error Could not get a valid HTTPS certificate
HTTPS: Request error Could not get a valid HTTPS certificate

Above errors appear when trying to remotely connect from https://url:12470 and http server does not work only

**Comment by jaruba** [comment]
@ashwarsadh there is indeed an issue with our SSL certificate, we're looking into it

**Comment by jaruba** [comment]
@ashwarsadh we checked and there doesn't seem to be an issue with our SSL certs, please check for the following:
- Go to Stremio's Settings page
- Select "Streaming" from the left panel
- Ensure that you have selected your correct LAN IP from the dropdown under "Enable Remote HTTPS Connections"
- Restart Stremio
- Go to Stremio's Settings page again
- Selected "Streaming" from the left panel again
- Check if you have an area entitled "Streaming HTTPS Endpoint"
- Press "Copy" next to the HTTPS Endpoint URL
- Try opening that page in the browser

It should be noted that `https://local.strem.io:12470` is not your remote HTTPS endpoint and should not be used directly, the HTTPS endpoint for your server is the one that is shown in Stremio's Settings.

**Comment by ashwarsadh** [comment]
I have attached Screenshots of configuration.
the HTTPS configuration.
Problem is https endpoint URL generated by Stremio points to Local IP Address (by checking A record Lookup or Ping)
but when we want to access my Stremio Server from Remote Computer or other network then obviuosly URL wont work as it will try to load Lan IP of Server Computer (192.168.1.254 in this example)
So, other way is to open Ports 12470 / 11470 in firewall for Stremio, then open Public IP Address of Server or Dynamic DNS hostname (noip etc) to access Stremio Server. (In this example I am accessing from my 4g Network, while Stremio Server is running on wifi)
when we open https://ServerWanIP:12470 it fails to load due to certificate mismatch.

There are 2 Solutions I Advise :
1. Provide option to enter your own Public IP / Dynamic DNS Domain name in place of Dropdown menu for "Enable Remote  HTTPS Connections" Dropdown.

2. Or allow invalid Certificates to connect to Stremio Server.

Current system of dropdown will only work if Server is directly connected to Internet and not behind a NAT

![Screenshot_20210708-204158__01](https://user-images.githubusercontent.com/24552398/124947407-6d7d2400-e02d-11eb-8a70-1a4d07bbb1bd.jpg)

![Screenshot_20210708-204202__02](https://user-images.githubusercontent.com/24552398/124947398-6c4bf700-e02d-11eb-9f99-cb567726d136.jpg)

![stremio config](https://user-images.githubusercontent.com/24552398/124946149-673a7800-e02c-11eb-9e85-1fdb761b0e31.jpg)
![A record lookup](https://user-images.githubusercontent.com/24552398/124946156-69043b80-e02c-11eb-8ede-f87dfa66b768.jpg)

**Comment by jaruba** [comment]
@ashwarsadh I'm afraid that Stremio never did support remote connection from outside of your LAN, this is a security issue and we will never add support for that. The SSL certificate was always, and will always be for LAN use only.

If you wish to setup remote access then this will need to be done manually, through any means necessary, using external services or applications, and by opening the required ports for external use also. Stremio will not handle this through it's own settings and technologies, as I said, it is a security issue that we do not wish to be accountable for.

**Comment by ioma8** [comment]
So how am I suppose to connect Stremio online UI from outside to my home based running Stremio app streaming server?

**Comment by jaruba** [comment]
@ioma8 

As stated before, this is a security issue that we do not wish to be accountable for. Through Stremio's internal features, this cannot be accomplished, and this is intentional.

We can't offer support for using the Stremio Server remotely through the internet, as it's not a Stremio feature. It can only be done if u already have networking and server configuration knowledge, which would make it obvious in regards to what is needed to get that working.
