### ISSUE TITLE
Touch support for player "hover" buttons

### ISSUE THREAD

**Issue by ioma8** [Stremio/stremio-shell#251]
I am using stremio on my touch laptop (Lenovo Yoga). While most features work out of the box with touch (scrolling, regular buttons, carousels etc), the "menus" bottom right in player mode can't be opened by touch. They are "open-on-mouse-over" menus and that means when using my laptop in touch-only style, I cant change subtitles, cast to chromecast etc. See screenshot at to what buttons I am talking about. Clicking on them with touch does nothing.

![image](https://user-images.githubusercontent.com/6624752/127857977-7a826ac3-d16f-40f9-bebf-7ce038bfa4e5.png)

**Comment by jaruba** [comment]
I created an issue for this at the appropriate repository. Will close this one as adding touch support is not related to the Stremio Shell directly.

**Comment by ioma8** [comment]
Okay might I ask what is appropriate repository?

**Comment by jaruba** [comment]
@ioma8 can u tell us more about ur issues with touch in Stremio, we've been trying to reproduce it and were unable to:
https://user-images.githubusercontent.com/40594253/127874288-b3d2e946-fb6a-44b0-8f13-068c80552551.mp4
