### ISSUE TITLE
stremio Big Sur error SDK 11.3 xcode 12.5.1 qt 5.12.11

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#253]
Undefined symbols for architecture x86_64:
  "_mpv_command_node", referenced from:
      MpvObject::command(QVariant const&) in mpv.o
  "_mpv_create", referenced from:
      MpvObject::MpvObject(QQuickItem*) in mpv.o
  "_mpv_error_string", referenced from:
      MpvObject::handle_mpv_event(mpv_event*) in mpv.o
  "_mpv_free_node_contents", referenced from:
      MpvObject::command(QVariant const&) in mpv.o
      MpvObject::getProperty(QString const&) in mpv.o
  "_mpv_get_property", referenced from:
      MpvObject::getProperty(QString const&) in mpv.o
  "_mpv_initialize", referenced from:
      MpvObject::MpvObject(QQuickItem*) in mpv.o
  "_mpv_observe_property", referenced from:
      MpvObject::observeProperty(QString const&) in mpv.o
  "_mpv_render_context_create", referenced from:
      MpvRenderer::createFramebufferObject(QSize const&) in mpv.o
  "_mpv_render_context_free", referenced from:
      MpvObject::~MpvObject() in mpv.o
      MpvObject::~MpvObject() in mpv.o
      non-virtual thunk to MpvObject::~MpvObject() in mpv.o
      MpvObject::~MpvObject() in mpv.o
      non-virtual thunk to MpvObject::~MpvObject() in mpv.o
  "_mpv_render_context_render", referenced from:
      MpvRenderer::render() in mpv.o
  "_mpv_render_context_set_update_callback", referenced from:
      MpvRenderer::createFramebufferObject(QSize const&) in mpv.o
  "_mpv_set_option_string", referenced from:
      MpvObject::MpvObject(QQuickItem*) in mpv.o
  "_mpv_set_property", referenced from:
      mpv::qt::set_property(mpv_handle*, QString const&, QVariant const&) in mpv.o
  "_mpv_set_wakeup_callback", referenced from:
      MpvObject::MpvObject(QQuickItem*) in mpv.o
  "_mpv_terminate_destroy", referenced from:
      MpvObject::~MpvObject() in mpv.o
      MpvObject::~MpvObject() in mpv.o
      non-virtual thunk to MpvObject::~MpvObject() in mpv.o
      MpvObject::~MpvObject() in mpv.o
      non-virtual thunk to MpvObject::~MpvObject() in mpv.o
  "_mpv_wait_event", referenced from:
      MpvObject::on_mpv_events() in mpv.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [stremio.app/Contents/MacOS/stremio] Error 1
please advise

**Comment by core1024** [comment]
You are missing the MPV library. Check out the [build script](https://github.com/Stremio/stremio-shell/blob/master/.github/workflows/shell.yaml#L58-L59).
