### ISSUE TITLE
Request: on movie/TV-show details screen, allow to search about it on Google (and others if you wish) and select the text of the title

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#256]
This can help for the cases there are no trailers about it yet, or if you can't find much information about it via Stremio yet.

Another useful thing to be able to do here, is to be able to select the text of the title , and to have a button to copy it to clipboard.

I'm talking about this screen:

![image](https://user-images.githubusercontent.com/5357526/128492996-3df2ccb1-6c12-429c-93db-cd9fc64e4d31.png)

**Comment by AndroidDeveloperLB** [comment]
Another useful thing to be able to do here, is to be able to select the text of the title , and to have a button to copy it to clipboard.

**Comment by TRtomasz** [comment]
I don't really think this is a good idea. It does not go along with purpose of the application.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz What do you mean? The app already has such features. They are just not always available, or not always work.
This can help to get more information about what we are about to watch. Why would it be so bad to have it?
