### ISSUE TITLE
Respect XDG Base Directory standard? 

### ISSUE THREAD

**Issue by motorto** [Stremio/stremio-shell#260]
Would be possible to implement [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) ?

**Comment by TRtomasz** [comment]
Hi,
For sure it would be possible. But will it happen? I guess not since Linux users are the smallest user group.
As far i know on linux systems stremio files are in the following directories.
`/opt/stremio`
`~/.stremio-server`
`~/.local/share/Smart\ Code\ ltd/`
`~/.cache/Smart Code ltd/`

**Comment by motorto** [comment]
@TRtomasz could you point what files need to be modified in order to help me implement this ?
