### ISSUE TITLE
stremio crash

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#261]
[libmpv_render/videotoolbox] need >= OpenGL 3.0 for core rectangle texture support
[libmpv_render] Loading failed.
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
qml: onNavigationRequested: disallowed URL https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F127.0.0.1%3A11470#?loginFlow=desktop
please advise
macosx 10.15.7 Qt Creator 4.15.2
Based on Qt 5.15.2 (Clang 11.0 (Apple), 64 bit)
xcode 11.5

**Comment by jaruba** [comment]
@kata62 any reason why you are trying to build the project instead of just downloading it from the website?

**Comment by kata62** [comment]
Learning

**Comment by kata62** [comment]
I didn’t change any thing in code also I am not using command line

**Comment by kata62** [comment]
how I can correct it
