### ISSUE TITLE
Gmail Login

### ISSUE THREAD

**Issue by guilherme-tavares-py** [Stremio/stremio-shell#263]
A lot of people don't use Facebook and would be fast to create an account using gmail or other types of email.

**Comment by jaruba** [comment]
Please use the `stremio-features` repository for such requests: https://github.com/Stremio/stremio-features/issues

As the login methods are not part of the `stremio-shell` repository, they are part of the different UIs of each Stremio device specific app.

**Comment by guilherme-tavares-py** [comment]
Sorry
