### ISSUE TITLE
Aarch64 build

### ISSUE THREAD

**Issue by baarkerlounger** [Stremio/stremio-shell#269]
Would be great to have an arm (aarch64) build added to the flatpak builder/flathub. The source compiles and runs on arm debian devices but would be great to be able to install a flatpak directly on devices like a PineBookPro.

**Comment by shivasiddharth** [comment]
You can use these binaries for 64 bit arm systems.

**Comment by baarkerlounger** [comment]
Thanks, that's cool. It also seems easy enough to build but it would be great to get official support including links on the main site.

**Comment by andirsun** [comment]
Any news for this on arm64 linux platform like fedora asahi ?

**Comment by amruthwo** [comment]
Another vote for Asahi or general arm64 support in the flatpak.  I tried using Alexandru-Balan's Stremio-Install-Scripts for Fedora, but it failed due to an issue with the server.js probably because his scripts don't target arm devices.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Stremio/stremio-shell/issues/269#issue-1046626683

@baarkerlounger, shouldn't this be reported at https://github.com/flathub/com.stremio.Stremio/issues/new instead? @Flathub keeps their issue tracking open for their repositories to support devolved issue tracking.

**Comment by baarkerlounger** [comment]
Good point. Opened https://github.com/flathub/com.stremio.Stremio/issues/27 and closing this.

**Comment by SilverGreen93** [comment]
> You can use these binaries for 64 bit arm systems. https://github.com/shivasiddharth/Stremio-RaspberryPi/releases/tag/4.4.142

Just an update to say that this does not work on Rapsberry Pi 5 with 64bit Ubuntu 24.04. Apparently it can be built only on older 32bit systems.

**Comment by shivasiddharth** [comment]
The README GitHub - shivasiddharth/Stremio-RaspberryPi: Installer for
Stremio on Raspberry Pi
<https://github.com/shivasiddharth/Stremio-RaspberryPi?tab=readme-ov-file#installation-using-binaries-only-buster-and-bullseye>
clearly
says that. I wanted to save everyone's time, but still people end up
wasting their time.

With Regards
SHIVASIDDHARTH

**Comment by TommySilver3461** [comment]
Man that's really disappointing.
I have spent the whole day trying to make it work. I've come to the point that I can't install libmpv1_0.32.0-3_arm64.deb with the status "Error: Dependency is not satisfiable: libavcodec58 (>= 7:4.2)"
I've installed that, but it still gives me this error.

Please someone help. I spent so much money and it's not working.

**Comment by crorodriguezro** [comment]
This script helped me to install stremio  in asahi fedora
https://github.com/alexandru-balan/Stremio-Install-Scripts/blob/master/installStremioFedora.sh
