### ISSUE TITLE
No more stable releases?

### ISSUE THREAD

**Issue by gbschenkel** [Stremio/stremio-shell#270]
Hi, I would like to know if are you guys are going to release a new version with all sub-modules included.

I am asking because I want to create a SlackBuild(for Slackware distro) script for stremio-shell, but SlackBuilds.org use a archive instead a git repo to build the sources.

I thought to download it from the tags url(like https://github.com/Stremio/stremio-shell/archive/v4.4.142/stremio-4.4.142.tar.gz) , but that doesn't include the sub-modules.

**Comment by core1024** [comment]
Hi. We are not planning to merge the submodules any time soon. Currently the easiest way to use Stremio in Linux is via Flatpack. I am not familiar with Slackware but If you want a native package, you'd better look for a way to add a pre-compile script (hook) that pulls the needed dependencies beforehand.

**Comment by gbschenkel** [comment]
Thanks, I will check with the community (SlackBuilds.org) how and where we can host the source with the submodules downloaded. I think they use sourceforge.net. but thanks anyway. PS: Slackware don't use flatpak or snap.
