### ISSUE TITLE
Request: Add to Calendar, but not to My Library

### ISSUE THREAD

**Issue by Francis-Br** [Stremio/stremio-shell#271]
I found quite often the necessity of removing some item from My Library because I am already up-to-date with it. However, I am not removing it because otherwise I cannot know when the new episodes are available. It would be useful to have in My Library those series I have in queue to watch and also some mark for those I want to track in the Calendar and be alerted of.

Thanks for all your work. Stremio is fantastic!

**Comment by TRtomasz** [comment]
Hello,
Because this is something that would require a lot of changes and at the same wouldn't be very popular at this moment we will not do this, sorry.
