### ISSUE TITLE
the .deb package  is outdated in the website

### ISSUE THREAD

**Issue by alavaelian** [Stremio/stremio-shell#272]
while the windows exe version is the last  Stremio+4.4.142.exe
i am getting the stremio_4.4.137-1_amd64.deb for ubuntu or debian version from the website,  how i can get the lastest ?

**Comment by TRtomasz** [comment]
Hi, sorry about this, you can download it here https://dl.strem.io/shell-linux/v4.4.142/stremio_4.4.142-1_amd64.deb

**Comment by alavaelian** [comment]
thanks mate

**Comment by jaruba** [comment]
The website has been updated, but it may take some time for the cache to expire for the new links to show

**Comment by alavaelian** [comment]
what is the cache to expire
