### ISSUE TITLE
[Windows] Stremio prevents system from going to sleep mode, even when closed and minified to system tray

### ISSUE THREAD

**Issue by asafm7** [Stremio/stremio-shell#291]
Stremio is preventing the screen from turning off after the set time under power settings, even when closed but minimized to the system tray (Windows 11).

![image](https://user-images.githubusercontent.com/14274769/160920566-d7a243e4-ac49-43a7-82d5-9fa064960b26.png)

**Comment by TRtomasz** [comment]
should be fixed now please check with latest version

**Comment by asafm7** [comment]
Great. Thank you.
