### ISSUE TITLE
single mouse click to toggle play/pause

### ISSUE THREAD

**Issue by aluskler** [Stremio/stremio-shell#294]
I would like an option to pause and play the video using the mouse click on the screen. please add this configuration, it would help me a lot.

**Comment by TRtomasz** [comment]
Adding such functionality, that affects  core Stremio component, would cause a lot of troubles for our regular users. Perhaps this could be solved with some mous gestures support, but i don't think we have plans to add this in the future.

**Comment by aluskler** [comment]
sad

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado:segunda-feira, 2 de maio de 2022 04:58
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Stremio/stremio-shell] single mouse click to toggle play/pause (Issue #294)


Adding such functionality, that affects core Stremio component, would cause a lot of troubles for our regular users. Perhaps this could be solved with some mous gestures support, but i don't think we have plans to add this in the future.
