### ISSUE TITLE
M1 Native Support?

### ISSUE THREAD

**Issue by vedkothavade** [Stremio/stremio-shell#295]
Since #275, QT 5.15.9 and above now supports universal builds, so would updating be possible to produce native M1 builds? Apparently to support Windows 7 and macOS 10.13, the highest possible version is 5.15.2, but per https://github.com/crystalidea/macdeployqt-universal, it is still possible to build arm binaries with more complications. 

It seems that the current version is 5.9.5, so if there is another reason QT5 hasn't been updated (to support something else that was deprecated/discontinued), then it's fine as Rosetta 2 works, but battery life is less than ideal in my experience so if it is an easy substitution that would be great!

**Comment by TRtomasz** [comment]
Main reason is  that updating this component can introduce issues we are not able to test and verify locally.
