### ISSUE TITLE
Error while starting streaming server. Please consider re-installing Stremio from ...

### ISSUE THREAD

**Issue by jpointsman** [Stremio/stremio-shell#296]
After upgrading to nodejs 18.1.0 I got this error:

`[cplayer] mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.17.100
[cplayer]    libavcodec      59.18.100
[cplayer]    libavformat     59.16.100
[cplayer]    libswscale      6.4.100
[cplayer]    libavfilter     8.24.100
[cplayer]    libswresample   4.3.100
[cplayer] FFmpeg version: n5.0
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-static stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Waiting for scripts...
[cplayer] Set property: vo="libmpv" -> 1
[cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[cplayer] Set property: cache-default=15000 -> -3
[cplayer] Set property: cache-backbuffer=15000 -> -3
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122-dirty
[osd/libass] Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Done loading scripts.
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop
qml: Stremio Shell version: 4.4.142
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: skipping, possibly not running an installed app?
[libmpv_render] GL_VERSION='3.1 Mesa 22.0.2'
[libmpv_render] Detected desktop OpenGL 3.1.
[libmpv_render] GL_VENDOR='Intel'
[libmpv_render] GL_RENDERER='Mesa Intel(R) HD Graphics 3000 (SNB GT2)'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='1.40'
[libmpv_render] Loaded extension GL_ARB_sync.
[libmpv_render] Loaded extension GL_ARB_timer_query.
[libmpv_render] Loaded extension GL_ARB_get_program_binary.
[libmpv_render] Loaded extension GL_ARB_buffer_storage.
[libmpv_render] Loaded extension GL_ARB_arrays_of_arrays.
[libmpv_render] Loaded extension GL_ARB_debug_output.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'vaapi-egl'
[libmpv_render/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'cuda-nvdec'
Cannot load libcuda.so.1
[libmpv_render/cuda-nvdec] Failed to load CUDA symbols
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'drmprime-drm'
[libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display.
[libmpv_render] Loading failed.
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/yeti/.stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
Discovery of new external device "mpv" - MPV
(node:11366) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
[11330:11367:0504/185640.625997:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -202
js: TypeError: Failed to fetch
[11330:11367:0504/185640.963751:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -107
js: Access to fetch at 'https://twistmoe.vercel.app/catalog/series/twistmoeseries.json' (redirected from 'https://twistmoe.now.sh/catalog/series/twistmoeseries.json') from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Access to fetch at 'https://rarbg-torrentapi-stremio.herokuapp.com/catalog/other/local.json' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
[11330:11367:0504/185641.190824:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -107
js: server-crash 1 (node:11366) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
`

**Comment by jaruba** [comment]
@jpointsman hi, how are you using the server? how did you update node.js? are you saying that you are running the stremio server directly through your own nodejs installation?

**Comment by mohad12211** [comment]
Hey, I'm also facing this issue, I'm on archlinux.
installed stremio using this [package](https://aur.archlinux.org/packages/stremio-beta)
and nodejs is installed through pacman, from the official repositories.
with nodejs 18.1.0, or 18.0.0, I get this error.
if I downgrade to nodejs 17.9.0, the error doesn't appear.
this is the error:
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:268036) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
```
that appears as a message when I open the app. and this is the logs:
```
~ > stremio 
[cplayer] mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.17.100
[cplayer]    libavcodec      59.18.100
[cplayer]    libavformat     59.16.100
[cplayer]    libswscale      6.4.100
[cplayer]    libavfilter     8.24.100
[cplayer]    libswresample   4.3.100
[cplayer] FFmpeg version: n5.0
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-static stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Set property: vo="libmpv" -> 1
[cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[cplayer] Set property: cache-default=15000 -> -3
[cplayer] Set property: cache-backbuffer=15000 -> -3
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Waiting for scripts...
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122-dirty
[osd/libass] Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Done loading scripts.
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop
qml: Stremio Shell version: 4.4.142
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: skipping, possibly not running an installed app?
[libmpv_render] GL_VERSION='4.6.0 NVIDIA 510.68.02'
[libmpv_render] Detected desktop OpenGL 4.6.
[libmpv_render] GL_VENDOR='NVIDIA Corporation'
[libmpv_render] GL_RENDERER='NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.60 NVIDIA'
[libmpv_render] Loaded extension GL_NV_vdpau_interop.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'vaapi-egl'
[libmpv_render/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'cuda-nvdec'
[libmpv_render] Loading hwdec driver 'drmprime-drm'
[libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display.
[libmpv_render] Loading failed.
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/mohad/.stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
Discovery of new external device "mpv" - MPV
(node:269099) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
js: TypeError: Failed to fetch
js: server-crash 1 (node:269099) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
```
and then the error keeps reappearing every few seconds.

**Comment by jpointsman** [comment]
The error happens after updating the main repository of nodejs in arch. I switched to package nodejs-lts-gallium with nodejs v16.15.0 and the error disappeared.

**Comment by PR454D** [comment]
> After upgrading to nodejs 18.1.0 I got this error:
> 
> `[cplayer] mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects [cplayer] built on UNKNOWN [cplayer] FFmpeg library versions: [cplayer] libavutil 57.17.100 [cplayer] libavcodec 59.18.100 [cplayer] libavformat 59.16.100 [cplayer] libswscale 6.4.100 [cplayer] libavfilter 8.24.100 [cplayer] libswresample 4.3.100 [cplayer] FFmpeg version: n5.0 [cplayer] [cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca [cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-static stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib [cplayer] Waiting for scripts... [cplayer] Set property: vo="libmpv" -> 1 [cplayer] Set property: gpu-hwdec-interop="auto" -> 1 [cplayer] Set property: cache-default=15000 -> -3 [cplayer] Set property: cache-backbuffer=15000 -> -3 [cplayer] Set property: cache-secs=10 -> 1 [cplayer] Set property: audio-client-name="Stremio" -> 1 [cplayer] Set property: title="Stremio" -> 1 [cplayer] Set property: audio-fallback-to-null="yes" -> 1 [cplayer] Set property: audio-client-name="Stremio" -> 1 [cplayer] Set property: title="Stremio" -> 1 WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed. [osd/libass] libass API version: 0x1502000 [osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122-dirty [osd/libass] Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX) [osd/libass] Setting up fonts... [osd/libass] Using font provider fontconfig [osd/libass] Done. [cplayer] Done loading scripts. qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop qml: Stremio Shell version: 4.4.142 qml: **** Completed. Loading Autoupdater *** qml: Auto-updater: skipping, possibly not running an installed app? [libmpv_render] GL_VERSION='3.1 Mesa 22.0.2' [libmpv_render] Detected desktop OpenGL 3.1. [libmpv_render] GL_VENDOR='Intel' [libmpv_render] GL_RENDERER='Mesa Intel(R) HD Graphics 3000 (SNB GT2)' [libmpv_render] GL_SHADING_LANGUAGE_VERSION='1.40' [libmpv_render] Loaded extension GL_ARB_sync. [libmpv_render] Loaded extension GL_ARB_timer_query. [libmpv_render] Loaded extension GL_ARB_get_program_binary. [libmpv_render] Loaded extension GL_ARB_buffer_storage. [libmpv_render] Loaded extension GL_ARB_arrays_of_arrays. [libmpv_render] Loaded extension GL_ARB_debug_output. [libmpv_render] GL_*_swap_control extension missing. [libmpv_render] Testing FBO format rgba16f [libmpv_render] Using FBO format rgba16f. [libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0). [libmpv_render] No advanced processing required. Enabling dumb mode. [libmpv_render] Loading hwdec driver 'vaapi-egl' [libmpv_render/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends. [libmpv_render] Loading failed. [libmpv_render] Loading hwdec driver 'cuda-nvdec' Cannot load libcuda.so.1 [libmpv_render/cuda-nvdec] Failed to load CUDA symbols [libmpv_render] Loading failed. [libmpv_render] Loading hwdec driver 'drmprime-drm' [libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display. [libmpv_render] Loading failed. hls executables located -> { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null } Using app path -> /home/yeti/.stremio-server Enabling casting... Discovery of new external device "vlc" - VLC Discovery of new external device "mpv" - MPV (node:11366) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (Use `node --trace-deprecation ...` to show where the warning was created) /opt/stremio/server.js:135945 details.family = details.family.toLowerCase(); ^
> 
> TypeError: details.family.toLowerCase is not a function at /opt/stremio/server.js:135945:39 at Array.filter () at /opt/stremio/server.js:135944:37 at Array.map () at Object.address (/opt/stremio/server.js:135939:37) at Server. (/opt/stremio/server.js:135075:37) at Server.emit (node:events:527:28) at Server.emit (node:domain:475:12) at emitListeningNT (node:net:1414:10) at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
> 
> Node.js v18.1.0 [11330:11367:0504/185640.625997:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -202 js: TypeError: Failed to fetch [11330:11367:0504/185640.963751:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -107 js: Access to fetch at 'https://twistmoe.vercel.app/catalog/series/twistmoeseries.json' (redirected from 'https://twistmoe.now.sh/catalog/series/twistmoeseries.json') from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. js: Access to fetch at 'https://rarbg-torrentapi-stremio.herokuapp.com/catalog/other/local.json' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. [11330:11367:0504/185641.190824:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -107 js: server-crash 1 (node:11366) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (Use `node --trace-deprecation ...` to show where the warning was created) /opt/stremio/server.js:135945 details.family = details.family.toLowerCase(); ^
> 
> TypeError: details.family.toLowerCase is not a function at /opt/stremio/server.js:135945:39 at Array.filter () at /opt/stremio/server.js:135944:37 at Array.map () at Object.address (/opt/stremio/server.js:135939:37) at Server. (/opt/stremio/server.js:135075:37) at Server.emit (node:events:527:28) at Server.emit (node:domain:475:12) at emitListeningNT (node:net:1414:10) at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
> 
> Node.js v18.1.0 `

yes me too

**Comment by core1024** [comment]
Currently Stremio uses the system's node version. It is symlinked to `/opt/stremio` where the application looks for the executable.
Our Flatpak package uses [node v5.14.0](https://github.com/flathub/com.stremio.Stremio/blob/master/com.stremio.Stremio.json#L39-L40).
As a temporary workaround until we fix this issue, you can either download that exact version of NodeJS https://nodejs.org/dist/latest-v15.x/node-v15.14.0-linux-x64.tar.xz with sha256: `f40a52c77a5a98203d24d6e5213c1a189bfc9736d0d9f667cb61151e9431b2a8` and replace the `node` executable in `/opt/stremio` or install the [Flatpak](https://flathub.org/apps/details/com.stremio.Stremio) package. This will make the application operational and will not affect the system update.

We will let you know when we have a permanent fix.

**Comment by hajking** [comment]
you dont need to downgrade node.js

[https://www.reddit.com/r/Stremio/comments/uic760/error_while_starting_streaming_server_please/](url)

**Comment by hajking** [comment]
the command to fix bug

sudo sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' /opt/stremio/server.js

**Comment by TaylanTatli** [comment]
> the command to fix bug
> 
> sudo sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' /opt/stremio/server.js

It's working, thank you. Here is a patch for AUR users:
```patch
diff --git a/PKGBUILD b/PKGBUILD
index a6fb7a8..9a62873 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -7,7 +7,7 @@ pkgdesc='A one-stop hub for video content aggregation (Movies, TV shows, series,
 arch=('x86_64')
 url='https://www.stremio.com/'
 license=('GPL3')
-depends=('mpv' 'nodejs-lts-gallium' 'openssl' 'qt5-webengine' 'qt5-base' 'qt5-declarative'
+depends=('mpv' 'nodejs' 'openssl' 'qt5-webengine' 'qt5-base' 'qt5-declarative'
           'qt5-quickcontrols' 'qt5-quickcontrols2' 'qt5-translations' 'qt5-webchannel')
 makedepends=('git' 'cmake' 'librsvg')
 source=("git+https://github.com/Stremio/stremio-shell.git#tag=v${pkgver}"
@@ -35,6 +35,7 @@ prepare() {
     # do not download server.js during 'make'
     ln -s "../stremio-${pkgver}-server.js" stremio-shell/server.js
     patch -d stremio-shell -Np1 -i "${srcdir}/010-stremio-do-not-download-server-js.patch"
+    sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' ${srcdir}/stremio-${pkgver}-server.js
 }
 
 build() {
```

**Comment by hajking** [comment]
> > the command to fix bug
> > sudo sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' /opt/stremio/server.js
> 
> It's working, thank you. Here is a patch for AUR users:
> 
> ```diff
> diff --git a/PKGBUILD b/PKGBUILD
> index a6fb7a8..9a62873 100644
> --- a/PKGBUILD
> +++ b/PKGBUILD
> @@ -7,7 +7,7 @@ pkgdesc='A one-stop hub for video content aggregation (Movies, TV shows, series,
>  arch=('x86_64')
>  url='https://www.stremio.com/'
>  license=('GPL3')
> -depends=('mpv' 'nodejs-lts-gallium' 'openssl' 'qt5-webengine' 'qt5-base' 'qt5-declarative'
> +depends=('mpv' 'nodejs' 'openssl' 'qt5-webengine' 'qt5-base' 'qt5-declarative'
>            'qt5-quickcontrols' 'qt5-quickcontrols2' 'qt5-translations' 'qt5-webchannel')
>  makedepends=('git' 'cmake' 'librsvg')
>  source=("git+https://github.com/Stremio/stremio-shell.git#tag=v${pkgver}"
> @@ -35,6 +35,7 @@ prepare() {
>      # do not download server.js during 'make'
>      ln -s "../stremio-${pkgver}-server.js" stremio-shell/server.js
>      patch -d stremio-shell -Np1 -i "${srcdir}/010-stremio-do-not-download-server-js.patch"
> +    sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' ${srcdir}/stremio-${pkgver}-server.js
>  }
>  
>  build() {
> ```

Nema problema. We live in a same society.
