### ISSUE TITLE
The Android version does not offer ways to copy download/magnet links, or context menu

### ISSUE THREAD

**Issue by Kabouik** [Stremio/stremio-shell#300]
On Linux, Stremio offers download/magnet links in the bottom right, but this is not available in the Android version as far as I can tell. There's also no right click (or long click) for the extra options that are available in the context menu of desktop versions. I believe these would be valuable additions to the Android version.

**Comment by TRtomasz** [comment]
Please use https://github.com/Stremio/stremio-features/issues repository for creating new feature requests.
