### ISSUE TITLE
[Bug] Stremio tray icon is not visible on light theme in windows 11

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-shell#311]
![ysM5MPAXC7](https://user-images.githubusercontent.com/47380919/187789516-1c4f2b7c-583c-433d-9dd7-667eeba6c722.png)
As shown in the image, the tray icon is not visible on light theme in windows 11

**Comment by TRtomasz** [comment]
i can see it on the screenshot and i have lifht theme right now and it is normally visible

**Comment by TRtomasz** [comment]
right now i know why it is better visible,
you can try enable this option
![image](https://user-images.githubusercontent.com/40594253/229528340-ce462173-1f46-49ad-b29d-60b7dc373318.png)
