### ISSUE TITLE
run workflows

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#358]
operating system Mac ventura
% act --list                       
Stage  Job ID             Job name            Workflow name  Workflow file  Events                    
0      build              build               Flatpak        flatpak.yaml   push,pull_request,schedule
0      build              build               Shell          shell.yaml     push,pull_request,schedule
0      slackNotification  Slack Notification  Shell          shell.yaml     schedule,push,pull_request
what is command line to build for mac

**Comment by core1024** [comment]
The build process for Mac OS and Linux is [pretty much the same](https://github.com/Stremio/stremio-shell/blob/master/release.makefile#L35-L37). Once you have installed all the necessary dependencies and configured the environment you use `cmake` to generate the the build script (we use `make` in the CI) and then you [run it](https://github.com/Stremio/stremio-shell/blob/master/.github/workflows/shell.yaml#L64-L65).

The difference between Mac OS and Linux is that after you've built the shell, you need to copy the binaries for `ffmpeg`, `ffprobe` and `node` as well as the `server.js` file in the `stremio.app/Contents/MacOS` and also use the `macdeployqt` tool to copy the Qt related dependencies. Lastly you need to copy `libcrypto.3.dylib` to `stremio.app/Contents/Frameworks`. Just like we do in our [build script](https://github.com/Stremio/stremio-shell/blob/master/.github/workflows/shell.yaml#L67-L89)
