### ISSUE TITLE
developer_id_app.p12 and developer_id_Installer.p12 password

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#359]
mbat@Mac-mini mac % source keychain_profile 
security: SecKeychainCreate build.keychain: A keychain with the same name already exists.
security: SecKeychainSetSettings build.keychain: 
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
security: SecItemCopyMatching: The specified item could not be found in the keychain.

what are the password for above certificates
I am using openssl@1.1

**Comment by core1024** [comment]
Hello. You don't need our certificates in order to build the application. The certificates are used for signing it so when someone download the DMG, the OS can verify that this is official release from us - the Stremio team.
