### ISSUE TITLE
build mac

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#360]
what are the commands required to get this result
![Screen Shot 2023-09-17 at 10 49 32 AM](https://github.com/Stremio/stremio-shell/assets/83540693/0a22dfa2-5146-4300-9f8b-b5ccb9b831d8)

**Comment by core1024** [comment]
The workflow configuration is [here](https://github.com/Stremio/stremio-shell/blob/master/.github/workflows/shell.yaml).
