### ISSUE TITLE
Scrolling laggy on Windows

### ISSUE THREAD

**Issue by PalmTamino** [Stremio/stremio-shell#369]
https://cdn.discordapp.com/attachments/1092185511998783498/1157395193084002386/VID_20230929_211407.mp4?ex=651873c5&is=65172245&hm=cdbbc730c905dd9df4d67da489c05a971537e677c0c6effedf17fd98493cb377&

Ryzen 5 3600
RTX 2070 Super
Windows 11 Pro

**Comment by TRtomasz** [comment]
Here is link to the experimental new version of our shell https://drive.google.com/drive/folders/1RTN6QH1rPUz64Dy13g15qrqYNrv290zG?usp=sharing  There are two files `stremio-shell-ng.exe` and `mpv.dll` after downloading them you simply have to put them next to original `stremio.exe` file and start. Please check out if it is still happening with this new version.

**Comment by PalmTamino** [comment]
> Here is link to the experimental new version of our shell https://drive.google.com/drive/folders/1RTN6QH1rPUz64Dy13g15qrqYNrv290zG?usp=sharing  There are two files `stremio-shell-ng.exe` and `mpv.dll` after downloading them you simply have to put them next to original `stremio.exe` file and start. Please check out if it is still happening with this new version.

Hey, i'm on holidays currently, but is the problem fixed now completely, or do i have to use this still, i will come back on Tuesday.

**Comment by TRtomasz** [comment]
@PalmTamino  you can tell me if it is fixed for you :P

**Comment by ashu570** [comment]
@TRtomasz  Hi, I have had the same issue for a while, and the update you have provided worked really nicely. However I have faced the following problems while using the updates,
1. The app crashes and closes if I open the full-screen mode.
2. The video playback seems a bit laggy (The video doesn't buffer but I can feel it's running just a little bit slower )
