### ISSUE TITLE
build stremio mac

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#370]
during build stremio on mac gives error
[Shell/build]   ✅  Success - Main Server
[Shell/build] ⭐ Run Main Fix dependencies
[Shell/build]   ✅  Success - Main Fix dependencies
[Shell/build] ⭐ Run Main Testdrive
[Shell/build]   ✅  Success - Main Testdrive
[Shell/build] ⭐ Run Main Rename the app
[Shell/build]   ✅  Success - Main Rename the app
[Shell/build] ⭐ Run Main Setup keychain
| security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
[Shell/build]   ❌  Failure - Main Setup keychain
[Shell/build] exit status 1
[Shell/build] 🏁  Job failed
Error: Job 'build' failed

**Comment by TRtomasz** [comment]
it was explained before - https://github.com/Stremio/stremio-shell/issues/359
