### ISSUE TITLE
Shoul be better have consistency in the dropdown for seasons

### ISSUE THREAD

**Issue by josuejs23** [Stremio/stremio-shell#373]
The dropdown that show the serie's seasons should have the same style that the button has, the ui has no consistency.
<img width="616" alt="Screenshot 2023-10-17 at 5 18 28 PM" src="https://github.com/Stremio/stremio-shell/assets/86853211/45f2cfff-49fa-4e7c-b1b5-30cd2adf0d37">

**Comment by TRtomasz** [comment]
This is how component looks in a browser, it will not be changed in stremio 4.
