### ISSUE TITLE
stremio:// link for titles

### ISSUE THREAD

**Issue by brigazvi** [Stremio/stremio-shell#378]
I'm working on a _Watch on Stremio_ addon for Firefox (and maybe other browsers). it should add a _Watch on Stremio_ button to IMDb, Trakt, and other popular websites.
I want to use a link that opens up in the Stremio shell.
I don't know if there is something like that yet. I know we have it for plugins but yet to find something like that for titles. the share button on mobile and web versions is just a link to a page asking to download Stremio.
thanks for an amazing app that  I use daily!

**Comment by core1024** [comment]
You can use the `stremio://` protocol indeed. For more information you can check out our documentation about deep links and namely the [Detail section](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deep-links.md#detail).
Deep links are supported both in Android and desktop version of Stremio.

**Comment by brigazvi** [comment]
Thanks. That is what I was looking for!
