### ISSUE TITLE
Guest Login Error.

### ISSUE THREAD

**Issue by artivision** [Stremio/stremio-shell#383]
I do guest login and everything works. Then i quit Stremio. Then i start Stremio again and booom:

`qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop`

Wile my custom plugins still work, the shell is annoying. Someone missed an `IF`. So after a first guest login should do:

`qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=guest`

Kudos to the one made the mistake, you are an `exceptional worker / manager`.

**Comment by TRtomasz** [comment]
this is on purpose, guest login are not being remebered.
