### ISSUE TITLE
Bug: now both on Android and on Windows, can't use the app with just guest login

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#390]
This is really annoying.
I could do it in the past just fine. I don't need an account.
Why does it force me to use one now?
Is there any workaround for this?

The only thing on PC (Windows) is to use "sign up with email" and then accept the terms, and then "guest login", but it asks it all the time...
This is on version 4.4.165.

**Comment by AndroidDeveloperLB** [comment]
I tried to use Facebook to register.
At first it worked, so I tried to remove the account and get back.
Didn't let me, so I tried to re-create the account, and now it doesn't let me do this either. It says "User not found"....
This is another bug. How come it doesn't let me get back by re-creating the account...

**Comment by TRtomasz** [comment]
This is not a bug you can't reuse same email/fb account for 3 years as we are obliated to store data for this long.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Is there anyone to talk with to let me enter again?
Why is it 3 years? This is very long...
Why does it say "User not found" ? I don't understand why this behavior.
Can't you remove my account completely so that I can re-create it again?
