### ISSUE TITLE
Installation on RaspberryPi5

### ISSUE THREAD

**Issue by Dirkinux** [Stremio/stremio-shell#392]
Hello,

I'm trying to install Stremio on my RaspbarryPi5 (bookworm).
At step 4, when I need to enter:

$ make -f release.makefile

It fails:
~/stremio-shell $ make -f release.makefile
mkdir -p build
cd build && cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="" ..
/bin/sh: 1: cmake: not found
make: *** [release.makefile:36: build/stremio] Error 127

Any Ideas how to proceed?

**Comment by TRtomasz** [comment]
Sorry we do not have any officiall documentation for installing on Rbpi you should ask the person who created instruction you are using.
