### ISSUE TITLE
Silent installer + command line options

### ISSUE THREAD

**Issue by hyperion4** [Stremio/stremio-shell#398]
/notorrentassoc - does not associate Stremio with .torrent files
/nodesktopicon - does not create Desktop shortcut for Stremio

They don't work. The silent installer even with them associates torrent files and creates the icon on desktop.
I think I am launching them properly. Please let me know if I don't.

"Stremio.exe" /S /notorrentassoc /nodesktopicon

I think the problem is NSIS actually. It always had issues with silent commandline options.
I don't understand why programs keep using NSIS for their installers.
Fortunately the installer of the Stremio service is using Inno Setup.
Inno Setup is well maintained and with a modern interface.

Please let me know if I am wrong and not lauching them properly.

**Comment by TRtomasz** [comment]
Here is our installator file, feel free to fix issues if you are able to find them
https://github.com/Stremio/stremio-shell/blob/master/windows/installer/windows-installer.nsi

**Comment by hyperion4** [comment]
> Here is our installator file, feel free to fix issues if you are able to find them https://github.com/Stremio/stremio-shell/blob/master/windows/installer/windows-installer.nsi

If I make a new installer with Inno Setup like the installer the Stremio service has will it be accepted?
I am not messing with NSIS and I will make an Inno Setup installer for my personal usage anyway.
Thank you for your reply.

**Comment by jaruba** [comment]
@hyperion4 we have been sending reports to tens of Antivirus companies for months regarding false-positives for Inno Setup because we use it in Stremio Service, progress is slow and in the meanwhile even more Antivirus software added it to lists

we have never had this issue with the Desktop app and NSIS, so we will continue to use NSIS for the Desktop app

while I understand ur point there doesn't seem to be much interest for Stremio users regarding the protocol association method, as it has been done like this for many many years, so I do not think that this is a valid reason to ditch NSIS for Inno at this point

**Comment by hyperion4** [comment]
> @hyperion4 we have been sending reports to tens of Antivirus companies for months regarding false-positives for Inno Setup because we use it in Stremio Service, progress is slow and in the meanwhile even more Antivirus software added it to lists
> 
> we have never had this issue with the Desktop app and NSIS, so we will continue to use NSIS for the Desktop app
> 
> while I understand ur point there doesn't seem to be much interest for Stremio users regarding the protocol association method, as it has been done like this for many many years, so I do not think that this is a valid reason to ditch NSIS for Inno at this point

Thank you for your reply.
I 've made a "quick to code" inno installer for personal usage "on top" of the nsis installer that installs stremio silently and reverts the torrent association, keeps the current association if it exists and removes the desktop icon.
If you are interested to try it, this is a link of it.
https://pixeldrain.com/u/oNSPYvTm
If you guys ever decide to use Inno I will for sure help on it, inno supports pascal coding too so it is easy to update a nsis installer to inno.
Thank you again for your reply.
