### ISSUE TITLE
Possible data leak

### ISSUE THREAD

**Issue by Redst0neFlux** [Stremio/stremio-shell#400]
Steps: 
- install https://github.com/Nekmo/dirhunt
- run dirhunt strem.io
- the output includes a large number of results such as https://www.stremio.com/br/change-password/<random user's email>@gmail.com/
I don't know how dirhunt works, but this seems like a vulnerability on stremio's part.

**Comment by jaruba** [comment]
that app can't find data leaks, it is an open directory scanner that parses html and checks the URL paths for possible paths that may allow browsing a folder (as far as i understand it)

**Comment by Redst0neFlux** [comment]
Yes but it somehow revealed emails to me. Stremio should not have user emails publicly available.

**Comment by jaruba** [comment]
We have investigated, this is not a data leak from the Stremio website, the app you mentioned does an API request at `https://web.archive.org/cdx/search/cdx?...`, there are exactly 10 emails in the list requested from the WayBack Machine archive

We will block the WayBack Machine crawler on that route and see what other changes can be made to ensure this does not happen with other crawlers.

We cannot know how WayBack Machine got a hold of these URLs, maybe linked somewhere in open forums, hard to tell.

Here is more information on this subject: https://mr23r0.medium.com/uncovering-the-secrets-the-potential-of-web-archive-in-bug-bounty-programs-322151fa4e63
