### ISSUE TITLE
Installation error on Fedora 30

### ISSUE THREAD

**Issue by brenoferreiralima** [Stremio/stremio-shell#87]
Error: 
 Problem: conflicting requests
  - nothing provides libQt5Quick.so.5(Qt_5.11.3_PRIVATE_API)(64bit) needed by stremio-4.4.52-1.fc29.x86_64

the current version of the libQt5Quick.so.5 in fedora is 5.12.1

**Comment by alexandru-balan** [comment]
Hi @brenoferreiralima 
I was reluctant to say this here but since you received no comment, may I suggest you take a look at my repo and use my script for installing it on F30? It will pull all the dependencies automatically.
https://github.com/alexandru-balan/Stremio-Install-Scripts

**Comment by Ivshti** [comment]
@alexandru-balan  We are considering dropping support for Fedora, so do you mind if we link your repo in stremio-shell?

**Comment by alexandru-balan** [comment]
I don't mind at all, I hope a lot of people will find the scripts usefull

**Comment by aliadolfo** [comment]
> Hi @brenoferreiralima
> I was reluctant to say this here but since you received no comment, may I suggest you take a look at my repo and use my script for installing it on F30? It will pull all the dependencies automatically.
> https://github.com/alexandru-balan/Stremio-Install-Scripts

Thanks!

**Comment by marcelloinfoweb** [comment]
> Hi @brenoferreiralima
> I was reluctant to say this here but since you received no comment, may I suggest you take a look at my repo and use my script for installing it on F30? It will pull all the dependencies automatically.
> https://github.com/alexandru-balan/Stremio-Install-Scripts

Obrigado!
