### ISSUE TITLE
When the shell is built against Qt 5.12.4-1 the webengine crashes

### ISSUE THREAD

**Issue by core1024** [Stremio/stremio-shell#92]
This could be a QT bug.

The web engine crashes with the following error:
```
qml: render process terminated with code 139 and status: 3
```
then it gets restarted and cashes again.

Tested on Arch Linux with Qt 5.12.4-1 and MPV 0.29.1

**Comment by inzar98** [comment]
Downgraded all qt deps and worked again :)

**Comment by Ivshti** [comment]
yep, this seems to solve it

```
sudo pacman -U /var/cache/pacman/pkg/qt5-webengine-5.12.3-2-x86_64.pkg.tar.xz
```

**Comment by inzar98** [comment]
> yep, this seems to solve it
> 
> ```
> sudo pacman -U /var/cache/pacman/pkg/qt5*5.12.3-2*
> ```

Im not using kde. But if anyone use plasma desktop that will be real issue to update plasma desktop. This issue need to be solved. Sorry bu I'm not developper :(

**Comment by konig1** [comment]
Any ETA on when the fix will be ready. Downgrading QT deps breaks the graphics so it's not really a fix.

**Comment by Ivshti** [comment]
@konig1 the newest qt in arch works fine

**Comment by AceLevy** [comment]
I'm experiencing this on Kubuntu 19.10.  I don't know how to tell exactly which version of QT I have.  If this is fixed upstream, is there a QT bug report for it somewhere?

**Comment by santiagofn** [comment]
Can confirm this also affects Ubuntu 19.10 w/ Qt 4.8.7.

```Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 0, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.14.100 (runtime 56.22.100)
[cplayer]    libavcodec      58.18.100 (runtime 58.35.100)
[cplayer]    libavformat     58.12.100 (runtime 58.20.100)
[cplayer]    libswscale      5.1.100 (runtime 5.3.100)
[cplayer]    libavfilter     7.16.100 (runtime 7.40.101)
[cplayer]    libswresample   3.1.100 (runtime 3.3.100)
[cplayer] ffmpeg version: 4.1.4-1build2
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --confdir=/etc/mpv --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --enable-dvdnav --enable-dvdread --enable-libmpv-shared --enable-libsmbclient --enable-sdl2 --enable-sndio --enable-zsh-comp --disable-build-date --enable-dvbin
[cplayer] List of enabled features: 52arch alsa asm atomics caca cdda cplayer cplugins debug-build drm drmprime dvbin dvdnav dvdread dvdread-common egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt libsmbclient linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband sdl2 sndio stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
Driver 'opengl-cb' has been replaced with 'libmpv'!
[cplayer] Set property: vo="opengl-cb" -> 1
Warning: property 'opengl-hwdec-interop' was replaced with 'gpu-hwdec-interop' and might be removed in the future.
[cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[cplayer] Set property: opengl-hwdec-interop="auto" -> 1
[cplayer] Set property: cache-default=15000 -> 1
[cplayer] Set property: cache-backbuffer=15000 -> 1
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
[cplayer] Waiting for scripts...
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[cplayer] Done loading scripts.
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop
qml: Stremio Shell version: 4.4.52
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: skipping, possibly not running an installed app?
[libmpv_render] GL_VERSION='3.1 Mesa 19.2.1'
[libmpv_render] Detected desktop OpenGL 3.1.
[libmpv_render] GL_VENDOR='X.Org'
[libmpv_render] GL_RENDERER='AMD TURKS (DRM 2.50.0 / 5.3.0-19-generic, LLVM 9.0.0)'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='1.40'
[libmpv_render] Loaded extension GL_ARB_sync.
[libmpv_render] Loaded extension GL_ARB_timer_query.
[libmpv_render] Loaded extension GL_ARB_get_program_binary.
[libmpv_render] Loaded extension GL_ARB_buffer_storage.
[libmpv_render] Loaded extension GL_ARB_shader_image_load_store.
[libmpv_render] Loaded extension GL_ARB_shader_storage_buffer_object.
[libmpv_render] Loaded extension GL_ARB_compute_shader.
[libmpv_render] Loaded extension GL_ARB_arrays_of_arrays.
[libmpv_render] Loaded extension GL_NV_vdpau_interop.
[libmpv_render] Loaded extension GL_ARB_debug_output.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'vaapi-egl'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'vdpau-glx'
[libmpv_render] Loading hwdec driver 'drmprime-drm'
[libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display.
[libmpv_render] Loading failed.
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/sfn/.stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
Discovery of new external device "mpv" - MPV
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
qml: render process terminated with code 139 and status: 3
(,,,,)```

**Comment by jscmal** [comment]
I am not experiencing the problem on my Ubuntu 19.10 MINIMAL installation.

I have installed some software that uses Qt, including stremio. They installed Qt libraries.

MAYBE, in the full installation, there is something that can affect Stremio ?!#@

**Comment by esteban-diaz** [comment]
I am experiencing the same problem on Ubuntu 19.10 with a minimal install ..
stremio generates same issue (render process terminated with code 139 and status: 3)

**Comment by crashbit666** [comment]
Yes, I have same issue. I updated from 19.04 to 19.10 and stremio fails.

**Comment by Ivshti** [comment]
Do you have Stremio installed from the deb, AppImage or you compiled it yourself?

**Comment by crashbit666** [comment]
I install Streamio from deb from official webpage

**Comment by esteban-diaz** [comment]
same here.. deb package from official website

**Comment by santiagofn** [comment]
+1 deb package from official website

**Comment by jsf15** [comment]
same problem here

**Comment by iagosoares95** [comment]
same problem with ubuntu 19.10 here

**Comment by bartart3d** [comment]
Just upgraded, same thing here..

**Comment by entraigas** [comment]
Hey is there any place to grab old stremio versions?

**Comment by Ivshti** [comment]
We tried reproducing it with Ubuntu 19.10 and the latest deb, without success

@core1024 will provide more details tomorrow

**Comment by michaldaniel** [comment]
I have been experiencing the same issue after upgrade from Ubuntu 19.04 to 19.10. I managed to get around it by installing QT locally and launching stremio with new  `export LD_LIBRARY_PATH=/home/morningbird/.qt/5.12.5/gcc_64/lib && stremio`

I find this issue really interesting as I too didn't experience this issue on another clean Ubuntu 19.10 installation, unfortunately done on completely different hardware but there are so many variables to isolate.

I looked into package QT installation and it's 5.12.4+dfsg-4ubuntu1 from eoan repositories, no irregularities inside `/usr/lib/x86_64-linux-gnu` either, only 5.12.4 version is present. It's really puzzling.

I'm commenting mainly for the benefit of those willing to do local QT installation as a temporary solution.

**Comment by jsf15** [comment]
@michaldaniel  Thanks for the comment, do you need a full Qt5 installation or only some packages?

**Comment by michaldaniel** [comment]
@jsf15 I wish I could help but I'm deep outside my technological comfort zone here.

**Comment by bartart3d** [comment]
Hi all, strange, but maybe it helps: after using 4.0.17 appimage version, which works just fine, I just tried the 4.4.52 deb-installed version I had the issue with, and guess what: it now works too.. Is it possible that running the 4.0.17 changes some config setting which makes the 4.4.52 work?

**Comment by fasetto** [comment]
> Hi all, strange, but maybe it helps: after using 4.0.17 appimage version, which works just fine, I just tried the 4.4.52 deb-installed version I had the issue with, and guess what: it now works too.. Is it possible that running the 4.0.17 changes some config setting which makes the 4.4.52 work?

I downloaded 4.0.17 AppImage and run 1 time. Then I ran the debian package version of streamio.
Now its working.. Hmm..?
I don't understand why it is working but thank you. Now I can watch some tv shows thanks to you.

**Comment by jsf15** [comment]
Wow, thank you that worked.
It may be usefull so below you find the output of installing the Appimage

**Comment by ctankutay** [comment]
same problem with after update to ubuntu 19.10 here then

https://www.appimagehub.com/p/1238391/
from files section download Stremio+4.0.17.appimage and make executable, make fun

or directly download
https://www.appimagehub.com/p/1238391/startdownload?file_id=1530276749&file_name=Stremio+4.0.17.appimage&file_type=application/x-executable&file_size=132692824

**Comment by santiagofn** [comment]
Appimage workaround worked! (WTH could be happening here?)

**Comment by vichaoss** [comment]
> same problem with after update to ubuntu 19.10 here then
> 
> Stremio+4.0.17.appimage and make executable, have fun
> 
> https://drive.google.com/drive/u/0/folders/16WFx1qz6uMu1QWyL4pEVap6Ov8-5skn0

worked!!!

**Comment by levisn1** [comment]
I confirm the workaround works.
Thank you!
