### ISSUE TITLE
cannot  make stremio

### ISSUE THREAD

**Issue by agordat1977** [Stremio/stremio-shell#96]
g++ -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o stremio singleapplication.o main.o mpv.o stremioprocess.o screensaver.o autoupdater.o systemtray.o razerchroma.o qclipboardproxy.o verifysig.o qrc_qml.o moc_singleapplication.o moc_singleapplication_p.o moc_mpv.o moc_stremioprocess.o moc_screensaver.o moc_mainapplication.o moc_autoupdater.o moc_systemtray.o moc_razerchroma.o moc_qclipboardproxy.o   -lmpv -lcrypto -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -lmpv
collect2: error: ld returned 1 exit status
Makefile:210: recipe for target 'stremio' failed
make: *** [stremio] Error 1

**Comment by Ivshti** [comment]
You need to install mpv (specifically libmpv along with its dev version)
