### ISSUE TITLE
Request: allow moving of entire window by dragging of its inner content

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#99]
As the title says.

**Comment by Ivshti** [comment]
used to be like this at some point in version 3.x - observing user behavior (from our friends/family) revealed that nobody knew about this

**Comment by AndroidDeveloperLB** [comment]
@Ivshti How come "nobody from family/friends knew about this" is the reason to remove it?
This is a common thing on various video players.
:(

**Comment by Ivshti** [comment]
First off, we asked people who use the app on a regular basis. Those people are not power users

Second, the more important reason we removed it is cause of the implementation difficulties

**Comment by AndroidDeveloperLB** [comment]
That's too bad.
